version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
     # - restore_cache:
          #key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      #- save_cache:
         # key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
         # paths:
          #  - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pwd; ls; 
            source venv/bin/activate;
            ./run-and-test-script.sh 
            sleep(120)
          background: true
            #PID = ps -ef | grep "gunicorn" | awk 'NR==1{print $2}'
            #kill -9 $PID
            #exit(0)
      - run:
          name: Killing Gunicorn
          command: |
            PID = ps -ef | grep "gunicorn" | awk 'NR==1{print $2}'
            kill -9 $PID
            exit(0)